//
// Copyright(C) 1993-1996 Id Software, Inc.
// Copyright(C) 2005-2014 Simon Howard
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// DESCRIPTION: Event handling.
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//

#include <stdlib.h>
#include <pthread.h>
#include "d_event.h"

#define MAXEVENTS 64

static event_t events[MAXEVENTS];
static int eventhead;
static int eventtail;
static int eventcount;
static pthread_mutex_t event_mutex = PTHREAD_MUTEX_INITIALIZER;

//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent (event_t* ev)
{
    pthread_mutex_lock(&event_mutex);

    // Coalesce consecutive mouse-motion events. This preserves the latest
    // position/buttons without allowing high-rate cursor input to consume the
    // complete keyboard queue.
    if (ev->type == ev_mouse && eventcount > 0)
    {
        int previous = (eventhead + MAXEVENTS - 1) % MAXEVENTS;
        if (events[previous].type == ev_mouse)
        {
            events[previous] = *ev;
            pthread_mutex_unlock(&event_mutex);
            return;
        }
    }

    // Keep the most recent state transitions when full. The old ring used
    // head == tail for both empty and full, causing a complete silent flush.
    if (eventcount == MAXEVENTS)
    {
        eventtail = (eventtail + 1) % MAXEVENTS;
        --eventcount;
    }
    events[eventhead] = *ev;
    eventhead = (eventhead + 1) % MAXEVENTS;
    ++eventcount;
    pthread_mutex_unlock(&event_mutex);
}

// Read an event from the queue.

event_t *D_PopEvent(void)
{
    static event_t popped_event;
    pthread_mutex_lock(&event_mutex);

    // No more events waiting.

    if (eventcount == 0)
    {
        pthread_mutex_unlock(&event_mutex);
        return NULL;
    }
    
    popped_event = events[eventtail];

    // Advance to the next event in the queue.

    eventtail = (eventtail + 1) % MAXEVENTS;
    --eventcount;

    pthread_mutex_unlock(&event_mutex);
    return &popped_event;
}

